language: ruby
cache: bundler
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "bundle exec rake db:create db:migrate"
  - "bundle exec rake parallel:create[2]"
  - "export PERCY_PARALLEL_NONCE=`date +%s`"
  - "export PERCY_PARALLEL_TOTAL=2"
script: 'xvfb-run -a bundle exec rake parallel:spec[2]'
